# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: registry.example.com/go-hello-world
      custom:
        buildCommand: sh buildx.sh
        dependencies:
          paths:
            - "**/*.go"
            - buildx.sh
            - go.mod
  tagPolicy:
    sha256: {}
  cluster:
    namespace: default
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
